### ISSUE TITLE
Framework is not running

### ISSUE THREAD

**Issue by arkadiyala** [swtestacademy/TestNGAllureReport#2]
I have cloned this framework and running testNG.xml as TestNG suite. I got below error message. could you please help me.
![image](https://user-images.githubusercontent.com/21693119/38970123-4ad6fa8a-4359-11e8-8248-870745d4224b.png)

**Comment by swtestacademy** [comment]
Hi would you try to change aspectj version?

**Comment by arkadiyala** [comment]
[Maven file.txt](https://github.com/swtestacademy/TestNGAllureReport/files/1928401/Maven.file.txt)

Please see attached pom.xml file i'm using. There is something wrong with pom.xml i think . I'm using - <aspectj.version>1.9.0</aspectj.version>
However i have 1.8.10 in my maven repository. Please see attached screenshot.
![image](https://user-images.githubusercontent.com/21693119/38996484-ea199b6e-43b0-11e8-8368-084c80872e9c.png)

Please help me.

**Comment by arkadiyala** [comment]
Please help me on below error message.

![image](https://user-images.githubusercontent.com/21693119/39015869-2152f62e-43e4-11e8-99e3-84f090ce1c18.png)

**Comment by swtestacademy** [comment]
I have just run the code without any problem. If you send me an email swtestacademy@gmail.com, I will share with you my project version. Everything works fine on my computer.

**Comment by swtestacademy** [comment]
When I will have time, I will connect your pc and we will check together. I
will write you When I am available. It looks environmental problem.

**Comment by arkadiyala** [comment]
Thank you sir.
